name: Python Build, Lint

on:
    push:
    release:
        types: [published]

jobs:
    build-test-lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout xero-python repo
              uses: actions/checkout@v4
              with:
                repository: XeroAPI/xero-python
                path: xero-python

            - name: Set up Python environment
              uses: actions/setup-python@v5
              with:
                python-version: '3.8'
                cache: 'pip'

            - name: Install dependencies
              run: |
                python -m venv venv
                source venv/bin/activate
                pip install --upgrade pip
                pip install black
                sudo pip install flake8
                pip install -r requirements.txt -r requirements/dev.txt
              working-directory: xero-python

            - name: Run Flake8
              run: flake8 xero_python
              working-directory: xero-python

            - name: Build package
              run: python setup.py sdist
              working-directory: xero-python

            # - name: Run Test
            #   run: |
            #     source venv/bin/activate
            #     pip install -r requirements/test.txt
            #     pytest -v
            #   working-directory: xero-python
    deploy:
        runs-on: ubuntu-latest
        needs: build-test-lint
        if: github.event_name == 'release' && github.event.action == 'published'

        steps:
            - name: Checkout xero-python repo
              uses: actions/checkout@v4
              with:
                repository: XeroAPI/xero-python
                path: xero-python

            - name: Set up Python environment
              uses: actions/setup-python@v5
              with:
                python-version: '3.8'
                cache: 'pip'

            - name: Install dependencies
              run: |
                python -m venv venv
                source venv/bin/activate
                pip install --upgrade pip
                pip install black
                sudo pip install flake8
                pip install -r requirements.txt -r requirements/dev.txt
              working-directory: xero-python

            - name: Build new package version
              run: python setup.py sdist
              working-directory: xero-python

            - name: Verify new package version
              run: ls -al dist
              working-directory: xero-python

            - name: Deploy to test PyPi
              env:
                TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
                TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
              run: twine upload --repository-url https://test.pypi.org/legacy/ dist/*
              working-directory: xero-python
