name: Deploy
on:
    release:
        types: [published]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout xero-python repo
              uses: actions/checkout@v4
              with:
                repository: XeroAPI/xero-python
                path: xero-python

            - name: Set up Python environment
              uses: actions/setup-python@v5
              with:
                python-version: '3.8'
                cache: 'pip'

            - name: Install dependencies
              run: |
                python -m venv venv
                source venv/bin/activate
                pip install --upgrade pip
                pip install black
                sudo pip install flake8
                pip install -r requirements.txt -r requirements/dev.txt
              working-directory: xero-python

            - name: Build new package version
              run: python setup.py sdist
              working-directory: xero-python

            - name: Verify new package version
              run: ls -al dist
              working-directory: xero-python

            - name: Deploy to test PyPi
              env:
                TWINE_USERNAME: __token__
                TWINE_PASSWORD: ${{ secrets.PYPI_APIKEY }}
              run: twine upload --repository-url https://test.pypi.org/legacy/ dist/*
              working-directory: xero-python
